### PR TITLE
Update 10.mass-spectrometers.md

### PR DESCRIPTION
**Pull request by lichenlady94**
Added some of the Q-TOF section, I will come back and add more but just wanted to send this as of now.

Please provide a description of your changes:

Please check the following about your suggested changed:
- [ ] The new text has one sentence per line
- [ ] preprints that are cited are listed as an issue for discussion and peer review

### CODE REVIEW

**Review by jessegmeyerlab — CHANGES_REQUESTED** [review]
Hi @lichenlady94 - thanks for getting started on this!! 

I just wanted to check if you are still planning to expand this and note that I am requesting at least 5 paragraphs for people to gain authorship. Also the figure would need to be original art instead of linking to existing figures. Also note that for the citations there is no space between the colon and the identifier, e.g. [@doi: 10.1021/jf063630e] should be [@doi:10.1021/jf063630e] and I think instead of @pubmed it needs to be @PMID: followed by the pubmed ID (not pubmedcentral id). 

Please let me know if you have any questions or need any help.

**Comment by lichenlady94** [comment]
Hey!


Definitely will be expanding more. I've just been rather swamped with
things at work but will be putting that on my things to do for the week!
I'll make the changes hopefully by this week, if not, next week by latest.

Susan

**Comment by lichenlady94** [comment]
@jessegmeyerlab is this one of the sections you were talking about?

**Comment by jessegmeyerlab** [comment]
> @jessegmeyerlab is this one of the sections you were talking about?

Yes this section but I think a postdoc in my lab wrote most of it. I will try to get what he has added if you want to help

**Pull request closed without merging**
