### PR TITLE
Update 13.biological-interpretation.md

### PR DESCRIPTION
**Pull request by norbertvolkmar**
work in progress

Please provide a description of your changes:

Please check the following about your suggested changed:
- [x] The new text has one sentence per line
- [x] preprints that are cited are listed as an issue for discussion and peer review

### CODE REVIEW

**Comment by norbertvolkmar** [comment]
I am aiming to develop this section further, especially related to the biological interpretation of structural proteomics data. This chapter might also benefit from a nice overview figure.

**Comment by jessegmeyerlab** [comment]
Thanks Norbert, will wait to review this until you give word

**Comment by jessegmeyerlab** [comment]
@norbertvolkmar here is a figure made by @ArokiaRex for this section - posting here so I remember to add after we merge your edits.

Any thoughts or suggestions would be appreciated

Fig_12_Biological interpretation_1 (1)

**Comment by norbertvolkmar** [comment]
Excellent. Beautiful figure - thank you!

**Comment by norbertvolkmar** [comment]
i am not sure when i'll be able to continue work on this section, so it might be best to approve the pull request for now?

**Comment by jessegmeyerlab** [comment]
> i am not sure when i'll be able to continue work on this section, so it might be best to approve the pull request for now?

Got it thanks. I will look at this today and might have comments.

**Comment by jessegmeyerlab** [comment]
Thanks for working on this. Overall there are some good concept additions here. Can you please add citations and make sure the text is one line per sentence? 

For the scope of a contribution to earn authorship, I'm hoping for at least five complete paragraphs. Each contribution needs to be assessed on a case by case basis though.

**Comment by norbertvolkmar** [comment]
No problem! I will keep working on it, just didn't have the time lately and didn't want to block anyone else from adding to it.


Norbert


________________________________

**Comment by norbertvolkmar** [comment]
just a general question (might be misplaced in this thread) - I haven't seen any activity on this review for 2 months now and the April 1 deadline has passed. Is this project still alive or has the prospect of submitting this review anytime soon been abandoned?

**Comment by jessegmeyerlab** [comment]
> just a general question (might be misplaced in this thread) - I haven't seen any activity on this review for 2 months now and the April 1 deadline has passed. Is this project still alive or has the prospect of submitting this review anytime soon been abandoned?

Thanks for checking in. 

I think the original deadline was too ambitious. On my end it was slowed down by me moving my lab across the country. We are getting settled jn now and if we can submit by the end of the year that would be more realistic. It will depend on who I hire and who we can recruit through social media to help with the project. I requested an extension from the journal. 

I recently received a section on databases from someone by email I need to add, and I know someone else is working on another section. I would be grateful for your contribution if you find the time.

**Comment by jessegmeyerlab** [comment]
@norbertvolkmar since it sounds like you are working on this section separately I will close this pull request for now and wait for your new one

**Pull request closed without merging**
