### PR TITLE
Update 04.protein-extraction.md

### PR DESCRIPTION
**Pull request by norbertvolkmar**
added additional bullet points

Please provide a description of your changes:

Please check the following about your suggested changed:
- [ ] The new text has one sentence per line
- [ ] preprints that are cited are listed as an issue for discussion and peer review

### CODE REVIEW

**Comment by jessegmeyerlab** [comment]
This is great thank you. I'm happy to add these bullets and will merge this pull request. I'm looking for a little more contribution to be included as an author. Would you be willing to expand on these topics ( or any other topic within the scope of this)? You could continue editing your branch and additional commits should show up here

**Comment by norbertvolkmar** [comment]
Absolutely! I was just trying out the system so far  but I am very much planning to be an active contributor and write a few sections in the coming weeks.

I’m looking forward to contributing to this fantastic team effort!

Norbert
________________________________

**Comment by jessegmeyerlab** [comment]
Thats great! Welcome!

**Comment by norbertvolkmar** [comment]
Hi,


I have been trying to edit a section in the 'contents' folder but I can't seem to submit a pull request. Instead I get this prompt:


'You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork norbertvolkmar/proteomics-tutorial, so you can send a pull request.'


I am sure I am overlooking something and this can be readily resolved.


Thank you for your help!


Best wishes,


Norbert


________________________________

**Comment by jessegmeyerlab** [comment]
Yes you want to make a branch as it suggests and then it will immediately bring you to the option of a pull request. That way your work lives in your copied repository and you don't lose your work while the changes can be reviewed. That also lets you continue making changes to your branch that get added to your pull request.

**Comment by norbertvolkmar** [comment]
Ok brilliant! I’ll do that

Many thanks,

Norbert

-----------------------------------------------------

Norbert Volkmar, PhD

Institute of Molecular Systems Biology
https://imsb.ethz.ch/
Picotti lab
ETH Zuerich
Switzerland

________________________________

**Comment by norbertvolkmar** [comment]
Thank you for your patience and advice. I am new to github and manubot and don't find it particularly intuitive, but I'm learning by trial and error. I will continue work on the 'Biological Interpretation' section in the coming days as soon as I can commit some more time to the shared effort!


Best wishes,


Norbert



________________________________

**Pull request merged**
