### PR TITLE
biological intepretation

### PR DESCRIPTION
**Pull request by ococrook**
Please provide a description of your changes:

add a biological intepretation section with computational methods includes
- GO enrichement
- databases such as string, reactome, and phosphositeplus
- structure prediction such as alphafold and rosetta fold
- tests based on personal lists
- molecular docking and dynamics
- isoform analysis
- BLAST
- protein language models
- network analysis
- intriscally disordered regions

Does not include experimental approaches

Please check the following about your suggested changed:
- [x] The new text has one sentence per line
- [x] preprints that are cited are listed as an issue for discussion and peer review

### CODE REVIEW

**Comment by jessegmeyerlab** [comment]
This is awesome thank you! 

Two questions: 

Are you still working on this or it's ready for review ?

I remember some discussion about people working together on some sections - is there anyone else who helped with this? If so please tag their github name so we can count lines to them when determining authorship.

**Comment by norbertvolkmar** [comment]
I am still to upload a section on orthogonal biological approaches. This section would focus on not only computational processing of the data but actually validating assumptions made based on the data (using both MS and MS-independent approaches)

**Comment by jessegmeyerlab** [comment]
Thanks for the information and thanks for adding the text Oliver. Someone else was also working on the same section at the same time and I just merged their changes with main. This is inevitable in an open project like this. It looks like you both added complementary ideas, so I need to try to merge the text. Please feel free to make a new PR trying to merge yours with theirs otherwise I can try to do it before next week Monday.

**Comment by ococrook** [comment]
That's no problem Jesse. I can have a look at merging the ideas together this week. I realise you want to get this finished asap

**Comment by jessegmeyerlab** [comment]
closing this for simplicity as I added Oliver's changes in #61 - @norbertvolkmar please open a new pull request with your additions when you have them

**Pull request closed without merging**
