### PR TITLE
Patch 5

### PR DESCRIPTION
**Pull request by norbertvolkmar**
Please provide a description of your changes:

Please check the following about your suggested changed:
- [x] The new text has one sentence per line
- [x] preprints that are cited are listed as an issue for discussion and peer review

### CODE REVIEW

**Comment by jessegmeyerlab** [comment]
Thanks for contributing! Looks like these the same changes from the pull request 6 months ago but with the addition of some text to the sample preparation section? 

It sounded like you were working on the biological interpretation section with Oliver- is that text coming later or is this that text? Thanks again.

**Comment by norbertvolkmar** [comment]
yes, simply added some text to the sample prep section. i'm still working together with Oliver on the biological interpretation section, but also jump between other parts of the review - wherever i think i can contribute and help out a little

________________________________

**Comment by jessegmeyerlab** [comment]
Thanks Norbert. 

Sorry for the confusion. It looks like you worked on the old version of that section before it was written recently:
https://github.com/jessegmeyerlab/proteomics-tutorial/blob/main/content/04.protein-extraction.md

This is probably due to you making edits on your fork which is not up to date with the main version. 

To avoid this in the future please make sure you start any edits from the main branch on the jessegmeyerlab repository instead of your fork, or click the button near the top right of the code list at your fork to sync your fork with the main branch before making changes. Please let me know if you have questions and sorry again for the confusion. 

Still it looks like you covered some good ideas in your text here that is not currently covered in the version we merged in late may. Do you want to try to incorporate those ideas in the current version by making a new pull request starting from the main branch or do you want me to try to reconcile those ideas with the current version? 

Thanks again for contributing and sorry again that the system is confusing to use.

**Comment by jessegmeyerlab** [comment]
Here is a link to the html form of the current sample prep section 
https://jessegmeyerlab.github.io/proteomics-tutorial/#protein-extraction

**Comment by jessegmeyerlab** [comment]
closing this given the other pull request on the new section

**Comment by norbertvolkmar** [comment]
No problem -  I will try and merge my edits with the main branch. Sorry for the inconvenience - I still find the system highly confusing.


Cheers,


Norbert


________________________________

**Pull request closed without merging**
